const state = {
  locationInfo: {
    id: 290,
    n: '深圳'
  },
  hotPlayMovies: [
    {
      actorName1: '徐峥',
      actorName2: '周一围',
      btnText: '',
      commonSpecial: '小人物因药变英雄实现自我救赎',
      directorName: '文牧野',
      img: 'http://img5.mtime.cn/mt/2018/06/21/102400.44145684_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: true,
      isIMAX: true,
      isIMAX3D: false,
      isNew: false,
      length: 116,
      movieId: 242167,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 144,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 3446
      },
      preferentialFlag: false,
      rDay: 5,
      rMonth: 7,
      rYear: 2018,
      ratingFinal: 8.8,
      titleCn: '我不是药神',
      titleEn: 'Dying To Survive',
      type: '剧情 / 喜剧',
      wantedCount: 1905
    },
    {
      actorName1: '李易峰',
      actorName2: '迈克尔·道格拉斯',
      btnText: '',
      commonSpecial: '生死游戏中直面人性的自私与残酷',
      directorName: '韩延',
      img: 'http://img5.mtime.cn/mt/2018/06/24/173836.91706768_1280X720X2.jpg',
      is3D: true,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: true,
      isNew: false,
      length: 132,
      movieId: 240989,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 140,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 774
      },
      preferentialFlag: false,
      rDay: 29,
      rMonth: 6,
      rYear: 2018,
      ratingFinal: 7.3,
      titleCn: '动物世界',
      titleEn: 'Animal World',
      type: '动作 / 剧情 / 悬疑',
      wantedCount: 2496
    },
    {
      actorName1: '克里斯·帕拉特',
      actorName2: '布莱丝·达拉斯·霍华德',
      btnText: '',
      commonSpecial: '恐龙纪元震撼回归 特效全面升级',
      directorName: '胡安·安东尼奥·巴亚纳',
      img: 'http://img5.mtime.cn/mt/2018/05/25/100000.65855294_1280X720X2.jpg',
      is3D: true,
      isDMAX: true,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: true,
      isNew: false,
      length: 128,
      movieId: 225759,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 117,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 424
      },
      preferentialFlag: false,
      rDay: 15,
      rMonth: 6,
      rYear: 2018,
      ratingFinal: 7.3,
      titleCn: '侏罗纪世界2',
      titleEn: 'Jurassic World: Fallen Kingdom',
      type: '动作 / 冒险 / 科幻',
      wantedCount: 8947
    },
    {
      actorName1: '刘纯燕',
      actorName2: '董浩',
      btnText: '',
      commonSpecial: '大头儿子一家在俄罗斯的奇幻冒险',
      directorName: '何澄',
      img: 'http://img5.mtime.cn/mt/2018/05/30/111001.79386218_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: true,
      length: 80,
      movieId: 256244,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 137,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 734
      },
      preferentialFlag: false,
      rDay: 6,
      rMonth: 7,
      rYear: 2018,
      ratingFinal: -1,
      titleCn: '新大头儿子和小头爸爸3：俄罗斯奇遇记',
      titleEn: 'New Happy Dad and Son 3:Adventure in Russia',
      type: '动画',
      wantedCount: 225
    },
    {
      actorName1: '崔永元',
      actorName2: '梁植',
      btnText: '',
      commonSpecial: '',
      directorName: '麦丽丝',
      img: 'http://img5.mtime.cn/mt/2018/06/29/112251.68964511_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: true,
      length: 99,
      movieId: 258572,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 27,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 74
      },
      preferentialFlag: false,
      rDay: 6,
      rMonth: 7,
      rYear: 2018,
      ratingFinal: -1,
      titleCn: '您一定不要错过',
      titleEn: '',
      type: '纪录片',
      wantedCount: 128
    },
    {
      actorName1: '韩素媛',
      actorName2: '',
      btnText: '',
      commonSpecial: '',
      directorName: '张跃斌',
      img: 'http://img5.mtime.cn/mt/2018/05/31/172744.58741178_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: true,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: true,
      length: 90,
      movieId: 257740,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 21,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 28
      },
      preferentialFlag: false,
      rDay: 6,
      rMonth: 7,
      rYear: 2018,
      ratingFinal: -1,
      titleCn: '细思极恐',
      titleEn: '',
      type: '恐怖 / 惊悚',
      wantedCount: 39
    },
    {
      actorName1: '张峻宁',
      actorName2: '石雨晴',
      btnText: '',
      commonSpecial: '',
      directorName: '孙杰',
      img: 'http://img5.mtime.cn/mt/2018/06/08/170450.52305733_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: true,
      length: 88,
      movieId: 258154,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 3,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 4
      },
      preferentialFlag: false,
      rDay: 6,
      rMonth: 7,
      rYear: 2018,
      ratingFinal: 0,
      titleCn: '只能活一个',
      titleEn: 'The Burns of Sin',
      type: '剧情 / 悬疑 / 犯罪',
      wantedCount: 19
    },
    {
      actorName1: '格雷格·T·尼尔森',
      actorName2: '霍利·亨特',
      btnText: '',
      commonSpecial: '超能家族时隔14年全员回归',
      directorName: '布拉德·伯德',
      img: 'http://img5.mtime.cn/mt/2018/05/23/125020.85709614_1280X720X2.jpg',
      is3D: true,
      isDMAX: true,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: true,
      isNew: false,
      length: 126,
      movieId: 223686,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 120,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 397
      },
      preferentialFlag: false,
      rDay: 22,
      rMonth: 6,
      rYear: 2018,
      ratingFinal: 8,
      titleCn: '超人总动员2',
      titleEn: 'The Incredibles 2',
      type: '动画 / 动作 / 冒险',
      wantedCount: 2522
    },
    {
      actorName1: '姜文',
      actorName2: '彭于晏',
      btnText: '',
      commonSpecial: '',
      directorName: '姜文',
      img: 'http://img5.mtime.cn/mt/2018/06/27/092636.32158363_1280X720X2.jpg',
      is3D: false,
      isDMAX: true,
      isFilter: false,
      isHot: false,
      isIMAX: true,
      isIMAX3D: false,
      isNew: false,
      length: 137,
      movieId: 223748,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 80,
        nearestShowDay: 1531468800,
        nearestShowtimeCount: 474
      },
      preferentialFlag: false,
      rDay: 13,
      rMonth: 7,
      rYear: 2018,
      ratingFinal: -1,
      titleCn: '邪不压正',
      titleEn: 'Hidden Man',
      type: '动作 / 剧情 / 喜剧',
      wantedCount: 3311
    },
    {
      actorName1: '西尔维斯特·史泰龙',
      actorName2: '黄晓明',
      btnText: '',
      commonSpecial: '史泰龙热力开打黄晓明秀功夫',
      directorName: '史蒂芬·C·米勒',
      img: 'http://img5.mtime.cn/mt/2018/06/06/122847.71875760_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: false,
      length: 93,
      movieId: 237446,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 58,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 109
      },
      preferentialFlag: false,
      rDay: 29,
      rMonth: 6,
      rYear: 2018,
      ratingFinal: 5,
      titleCn: '金蝉脱壳2',
      titleEn: 'Escape Plan 2: Hades',
      type: '动作 / 惊悚',
      wantedCount: 1227
    },
    {
      actorName1: '张国荣',
      actorName2: '张曼玉',
      btnText: '',
      commonSpecial: '这世界上有一种鸟是没有脚的',
      directorName: '王家卫',
      img: 'http://img5.mtime.cn/mt/2018/06/21/113853.36979689_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: false,
      length: 94,
      movieId: 10053,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 34,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 87
      },
      preferentialFlag: false,
      rDay: 25,
      rMonth: 6,
      rYear: 2018,
      ratingFinal: 8.3,
      titleCn: '阿飞正传',
      titleEn: 'Days of Being Wild',
      type: '剧情',
      wantedCount: 1360
    },
    {
      actorName1: '吴磊',
      actorName2: '梁家辉',
      btnText: '',
      commonSpecial: '',
      directorName: '张鹏',
      img: 'http://img5.mtime.cn/mt/2018/06/19/103712.29195367_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: false,
      length: 141,
      movieId: 232558,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 1,
        nearestShowDay: 1531382400,
        nearestShowtimeCount: 1
      },
      preferentialFlag: false,
      rDay: 13,
      rMonth: 7,
      rYear: 2018,
      ratingFinal: -1,
      titleCn: '阿修罗',
      titleEn: 'Asura',
      type: '奇幻 / 爱情 / 动作',
      wantedCount: 457
    },
    {
      actorName1: '道恩·强森',
      actorName2: '内芙·坎贝尔',
      btnText: '',
      commonSpecial: '',
      directorName: '罗森·马歇尔·瑟伯',
      img: 'http://img5.mtime.cn/mt/2018/06/26/145256.92156386_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: false,
      length: 0,
      movieId: 234573,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 1,
        nearestShowDay: 1531987200,
        nearestShowtimeCount: 1
      },
      preferentialFlag: false,
      rDay: 20,
      rMonth: 7,
      rYear: 2018,
      ratingFinal: -1,
      titleCn: '摩天营救',
      titleEn: 'Skyscraper',
      type: '动作 / 犯罪 / 剧情',
      wantedCount: 508
    },
    {
      actorName1: '小日向文世',
      actorName2: '深津绘里',
      btnText: '',
      commonSpecial: '全球大断电 为活下去拼了',
      directorName: '矢口史靖',
      img: 'http://img5.mtime.cn/mt/2018/06/12/102343.67282689_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: false,
      length: 117,
      movieId: 237536,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 14,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 25
      },
      preferentialFlag: false,
      rDay: 22,
      rMonth: 6,
      rYear: 2018,
      ratingFinal: 8.1,
      titleCn: '生存家族',
      titleEn: 'サバイバルファミリー',
      type: '喜剧',
      wantedCount: 291
    },
    {
      actorName1: '小沈阳',
      actorName2: '潘斌龙',
      btnText: '',
      commonSpecial: '小沈阳和潘斌龙勇闯台湾五湖帮',
      directorName: '小沈阳',
      img: 'http://img5.mtime.cn/mt/2018/06/05/091818.46413077_1280X720X2.jpg',
      is3D: false,
      isDMAX: false,
      isFilter: false,
      isHot: false,
      isIMAX: false,
      isIMAX3D: false,
      isNew: false,
      length: 100,
      movieId: 234987,
      nearestShowtime: {
        isTicket: true,
        nearestCinemaCount: 14,
        nearestShowDay: 1530864000,
        nearestShowtimeCount: 25
      },
      preferentialFlag: false,
      rDay: 15,
      rMonth: 6,
      rYear: 2018,
      ratingFinal: 4.4,
      titleCn: '猛虫过江',
      titleEn: 'A strong insect crossing the river',
      type: '喜剧 / 动作',
      wantedCount: 468
    }
  ]
}

export default state
